name: Update FGI

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Update Google Sheets
        run: python fetch.py
